### PR TITLE
Waits for fetch

### PR DESCRIPTION
**Pull request by Freak613**

### CODE REVIEW

**Comment by alfonso-presa** [comment]
I'm sorry. Due to the merge of #3 and it's dist update now this PR has conflicts... Code looks ok. Could you please rebase and squash. Thanks!

**Comment by Freak613** [comment]
Done.
How can I find what is these conflicts?

**Comment by alfonso-presa** [comment]
Conflicts are in the dist folder. You have to add a new remote to your local repo an then perform a rebase against that remote's master.

Also, I've merged your changes locally and tests are failing in all browsers. For firefox and chrome, I guess it's because the protactor capabilities configuration (it's should be at least firefox 39 and chrome 42 to support `fetch`), but for IE and for Safari, `fetch`is not yet supported. This makes the tests fail... I've sent you a PR with both issues solved ;-).

**Comment by Freak613** [comment]
Although I still don't understand what was the conflicts, I accepted your update and everything looks okay now.

**Comment by alfonso-presa** [comment]
Conflicts where because dist files were not included in #3 so I did commit https://github.com/alfonso-presa/protractor-testability-plugin/commit/270e20334fdb59b97686a4ac5bbb6ca4d152cda4 to solve that. Your changes for this PR did modify the dist files but they where not based against that commit, so conflicts where found as the list files were modified by both.

This one looks ok now :-). Could you please squash everything together. I know it's my bad because I sent you some additional commits but if I solve that myself I will be the commiter and I don't think that's fair as the feature is yours. Thanks!

**Comment by Freak613** [comment]
Done

**Comment by alfonso-presa** [comment]
Merged. Thanks!

**Pull request merged**
